
const requisitionDetailsItemModel = {
  id: '',
  storeId: '',
  storeName: null,
  createUser: null,
  createUserName: null,
  createTime: '',
  updateUser: null,
  updateTime: null,
  deleteFlag: null,
  tenantId: null,
  tenName: null,
  queryString: null,
  isSystem: null,
  delIds: null,
  delIdsList: null,
  page: 0,
  rows: 0,
  orderProperty: null,
  orderDirection: null,
  storeIds: null,
  applyOrderId: '',
  goodsId: '',
  goodsCode: '',
  goodsName: '',
  goodsSpec: null,
  purcUnitId: '',
  purcUnitName: '',
  purcUnitNum: null,
  unitId: '',
  unitName: '',
  unitNum: 0,
  remarks: '',
  sequence: 0,
  supplyId: null,
  supplyName: null,
  dualUnitId: null,
  dualUnitName: null,
  dualUnitNum: null,
  arrivalDate: null,
};
const cannManageItemModel = {
  id: '',
  storeId: '',
  goodsId: '',
  goodsCode: '',
  goodsName: '',
  goodsSpec: '',
  unitId: '',
  unitName: '',
  unitNum: '',
  ordUnitId: '',
  ordUnitName: '',
  ordUnitNum: '',
  ordAdjustNum: '',
  dualUnitId: '',
  dualUnitName: '',
  dualUnitNum: '',
  ordPrice: '',
  ordPriceNotax: '',
  taxRatio: '',
  goodsAmt: '',
  goodsAmtNotax: '',
  remarks: '',
  goodsQty: '',
  wareQty: '',
  unitPrice: '',
  unitPriceNotax: '',
  dualGoodsQty: '',
};
const stockOutDetailsItemModel = {
  id: null,
  goodsId: null,
  unitId: null,
  dualUnitId: null,
  ordUnitId: null,
  dualUnitFlag: null,
  dualWareQty: null,
  // 显示字段
  goodsCode: null,
  goodsName: null,
  goodsSpec: null,
  dualUnitName: null,
  dualGoodsQty: null,
  unitName: null,
  goodsQty: null,
  unitPrice: 0.00,
  goodsAmt: null,
  remarks: null,
};
const officialCheckDetailsItemModel = {
  id: '',
  storeId: '',
  storeName: null,
  createUser: null,
  createUserName: null,
  createTime: null,
  updateUser: null,
  updateTime: null,
  deleteFlag: 1,
  tenantId: null,
  tenName: null,
  queryString: null,
  isSystem: 1,
  orgType: null,
  delIds: null,
  delIdsList: null,
  page: 0,
  rows: 0,
  orderProperty: null,
  orderDirection: null,
  storeIds: null,
  depotCode: '',
  depotName: '',
  maxInoutDate: null,
  maxCheckDate: null,
  status: 1,
  remarks: null,
  defaultDepot: 0,
  distribId: null,
  dualGoodsQty: '',
  checkQty: '',
  accQty: '',
  dualAccQty: '',
  wareQty: '',
  unitName: '',
  goodsPrice: '',
  checkUnitName: '',
  profitPrice: '',
};

const priceListDetailsItemModel = {
  id: '',
  storeId: '',
  storeName: '',
  createUser: '',
  createUserName: '',
  createTime: '',
  updateUser: '',
  updateTime: '',
  deleteFlag: 0,
  tenantId: '',
  tenName: '',
  query: '',
  isSystem: '',
  orgType: '',
  delIds: '',
  delIdsList: '',
  page: 0,
  rows: 0,
  orderProperty: '',
  orderDirection: '',
  storeIds: '',
  inDepotId: '',
  outDepotId: '',
  depotId: '',
  token: '',
  billId: '',
  billNo: '',
  orgInfoId: '',
  orgInfoName: '',
  storeCode: '',
  goodsId: '',
  goodsName: '',
  goodsSpec: '',
  unitName: '',
  goodsPrice: 0,
  status: '',
  remarks: '',
  goodsCode: '',
  startDate: '',
  endDate: '',
  delStoreId: '',
  delGoodsId: '',
  updateUserName: '',
};
const orderTemplateDetailsItemModel = {
  id: '',
  storeId: '',
  storeName: null,
  createUser: null,
  createUserName: null,
  createTime: null,
  updateUser: null,
  updateTime: null,
  deleteFlag: 1,
  tenantId: null,
  tenName: null,
  queryString: null,
  isSystem: 1,
  orgType: null,
  delIds: null,
  delIdsList: null,
  page: 0,
  rows: 0,
  orderProperty: null,
  orderDirection: null,
  storeIds: null,
  depotCode: '',
  depotName: '',
  maxInoutDate: null,
  maxCheckDate: null,
  status: 1,
  remarks: null,
  defaultDepot: 0,
  distribId: null,
  dualGoodsQty: '',
  checkQty: '',
  accQty: '',
  dualAccQty: '',
  wareQty: '',
  unitName: '',
  goodsPrice: '',
  checkUnitName: '',
  profitPrice: '',
};
const stockOutDistributionDetailsItemModel = {
  // 隐藏字段
  id: null,
  goodsId: null,
  unitId: null,
  dualUnitId: null,
  ordUnitId: null,
  purcUnitId: null,
  applyId: null,
  // 显示字段
  applyBillNo: null,
  goodsCode: null,
  goodsName: null,
  goodsSpec: null,
  ordUnitName: null,
  ordUnitNum: null,
  outNum: null,
  wareNum: null,
  outDualNum: null,
  dualUnitNum: null,
  dualUnitName: null,
  purcUnitNum: null,
  purcUnitName: null,
  unitNum: null,
  unitName: null,
  remarks: null,
};
requisitionDetailsItemModel.renderErrorRules = true;
cannManageItemModel.renderErrorRules = true;
stockOutDetailsItemModel.renderErrorRules = true;
officialCheckDetailsItemModel.renderErrorRules = true;
orderTemplateDetailsItemModel.renderErrorRules = true;
stockOutDistributionDetailsItemModel.renderErrorRules = true;

module.exports = {
  requisitionDetailsItemModel,
  cannManageItemModel,
  stockOutDetailsItemModel,
  officialCheckDetailsItemModel,
  priceListDetailsItemModel,
  orderTemplateDetailsItemModel,
  stockOutDistributionDetailsItemModel,
};
